heavily wip updating to using nix
still using arch but using home-manager on top of
it to manage lots of things

diff --git a/.local/scripts/generic/beet-install b/.local/scripts/generic/beet-install
--- a/.local/scripts/generic/beet-install
+++ b/.local/scripts/generic/beet-install
@@ -1,5 +1,14 @@
 #!/usr/bin/env bash
-pipx install beets --python "$(pyenv-full-path 3.12.8)"
+if ! havecmd uv; then
+  echo 'Could not find uv on your $PATH' >&2
+  exit 1
+fi
+python_path="$(uv python find 3.12.8)"
+if [[ -z "$python_path" ]]; then
+  echo "Could not find python 3.12.8, run 'uv python install 3.12.8' to install it" >&2
+  exit 1
+fi
+pipx install beets --python "$python_path"
 pipx inject beets beets-filetote
 pipx inject beets discogs_client
 pipx inject beets pylast
diff --git a/.local/scripts/generic/pipx-run b/.local/scripts/generic/pipx-run
--- a/.local/scripts/generic/pipx-run
+++ b/.local/scripts/generic/pipx-run
@@ -11,7 +11,11 @@ declare path
 if [[ -f "$script" ]]; then
 	path="$script"
 else
-	path="$(which "$script")" || exit 1
+	path="$(command -v "$script")" || exit 1
+	if [[ ! -f "$path" ]]; then
+		printf "Could not find %s on your $PATH\n" "$path"
+		exit 1
+	fi
 fi
 shift
-exec python3 -m pipx run --path "$path" "$@"
+exec pipx run --path "$path" "$@"
