add yaml to rifle.conf

diff --git a/.local/scripts/linux/tiktok-update-rss-feeds b/.local/scripts/linux/tiktok-update-rss-feeds
--- a/.local/scripts/linux/tiktok-update-rss-feeds
+++ b/.local/scripts/linux/tiktok-update-rss-feeds
@@ -1,18 +1,17 @@
 #!/usr/bin/env bash
 
 contents="$(cat "$HOME/.config/newsraft/feeds")"
-usernames="$(spkglist "$XDG_DOCUMENTS_DIR/tiktok.txt")"
 
-while read -r line; do
-	if grep -q "rss/${line}.xml " <<<"$contents"; then
-		echo "Skipping @$line, already present" >&2
+while read -r username; do
+	if grep -q "rss/${username}.xml " <<<"$contents"; then
+		echo "Skipping @$username, already present" >&2
 		continue
 	fi
-	echo "Adding @$line" >&2
-	file="${HOME}/.cache/tiktok-local-rss/rss/${line}.xml"
+	echo "Adding @$username" >&2
+	file="${HOME}/.cache/tiktok-local-rss/rss/${username}.xml"
 	if [[ ! -f "$file" ]]; then
-		echo "While adding $line, $file not found" >&2
+		echo "While adding $username, $file not found" >&2
 		continue
 	fi
-	printf 'file://%s "%s"\n' "$file" "$line" >>"$HOME/.config/newsraft/feeds"
-done <<<"$usernames"
+	printf 'file://%s "%s"\n' "$file" "$username" >>"$HOME/.config/newsraft/feeds"
+done < <(spkglist "$XDG_DOCUMENTS_DIR/tiktok.txt")
